// Source: https://leetcode.com/problems/find-the-difference/description/
// Author: Diego Lee
// Date: 2018-08-17
//
// Description:
// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.

#include <iostream>
#include <string>
#include <unordered_map>

class Solution
{
    public:
        char findTheDifference(std::string s, std::string t)
        {
            std::unordered_map<char, int> hash;
            for (char ch : s)
            {
                ++hash[ch];
            }
            for (char ch : t)
            {
                if (--hash[ch] < 0)
                {
                    return ch;
                }
            }
            return ' ';
        }
};

void testFindTheDifference()
{
    Solution s;
    char ch =  s.findTheDifference("abcd", "bceda");
    assert(ch == 'e');
}

int main()
{
    testFindTheDifference();
    return 0;
}
