#!/usr/bin/env python
# encoding: utf-8

'''
Source: https://leetcode.com/problems/find-the-difference/description/
Author: Diego Lee
Date: 2018-08-17

Description:
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

import unittest

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        d = {}
        for ch in s:
            if d.has_key(ch):
                d[ch] += 1
            else:
                d[ch] = 1
        for ch in t:
            if d.has_key(ch):
                if d[ch] - 1 < 0:
                    return ch
                else:
                    d[ch] -= 1
            else:
                return ch
        return ' '

class TestSolution(unittest.TestCase):
    def testFindTheDifference(self):
        result = Solution().findTheDifference("abcd", "dcbae")
        self.assertEqual(result, 'e')

if __name__ == '__main__':
    unittest.main()
